### ISSUE TITLE
Bitmovin Native Flash fallback is not working in Firefox (native-flash.hls)

### ISSUE THREAD

**Issue by joe455** [bitmovin/bitmovin-javascript#58]
Unable to play Flash videos in Bitmovin player in Firefox. What could be the issue?

**Comment by SInCE** [comment]
Hi Joe, could you please explain the issue you are facing in more detail? 

Based on what you wrote so far, I think that you web server or storage is delivering everything with the same content type, instead of providing the appropriate content-type information for video/audio. Flash as well as other tools/browsers (e.g. Safari when playing HLS) are strict about the correct content-type information.

As this issue doesn't seem to be related to our Bitmovin Javascript API client in any way, you can also reach out to our support-team via support@bitmovin.com.

**Comment by joe455** [comment]
@SInCE Let me explain the issue. We implemented a solution to play AES-128 encrypted video by using native flash player with Adobe access DRM. While video is getting played in all browsers, Fire fox is giving the error Play back failed with error code 3000. 

While in other browsers play is working but seek is not working. Can you please help me to resolve the issue.

**Comment by LudoMichaud** [comment]
Hi Joe, 
As our support team already replied to your questions via email, I will close this issue for now. Please feel free to reach out to support@bitmovin.com again in case there is anything else we can hep you with.
